aled

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -16,58 +16,49 @@ jobs:
     container:
       image: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - name: run check
-        uses: actions/checkout@v3
-      - name: run check script
-        shell: bash
-        run: check.sh $(pwd) $(pwd)
-      - name: parsing coding style
-        shell: bash
-        run: |
-          if [ -s $(pwd)/coding-style-reports.log ]; then
-            while read -r line; do
-              morM=$(echo $line | cut -d ':' -f3)
-              filename=$(echo $line | cut -d ':' -f1)
-              line=$(echo $line | cut -d ':' -f2)
-              error_type=$(echo $line | cut -d ':' -f4)
-              echo "::${morM} coding style error:${filename}\#L${line} ::${error_type}"
-              done < coding-style-reports.log
-            exit 1
-          fi
+      - uses: actions/checkout@v3
+      - run: check.sh $(pwd) $(pwd)
+
   check_program_compilation:
     runs-on: ubuntu-latest
-    steps:
-      - name: before
-        uses: actions/checkout@v3
-      - name: make
-        shell: bash
-        run: make
-        timeout-minutes: 2
-      - name: clean
-        shell: bash
-        run: make fclean
-  run_test:
-    needs: check_program_compilation
-    runs-on: ubuntu-latest
-    container:
-      image: epitechcontent/epitest-docker
+    needs: [check_coding_style]
+    container: epitechcontent/epitest-docker
     timeout-minutes: 2
     steps:
-      - name: before
+      - name: Checkout the code
         uses: actions/checkout@v3
-      - name: run tests
-        run: make tests_run
-        timeout-minutes: 2
-  push_to_mirror:
-    needs: run_test
+      - name: Build the code
+        run: make
+      - name: Clean the code
+        run: make clean
+      - name: Check for executables
+        run: |
+          for exe in $(echo $EXECUTABLES | tr "," "\n"); do
+            if [ ! -x $exe ]; then
+              echo "Error: $exe not found or not executable"
+              exit 1
+            fi
+           done
+
+  run_tests:
     runs-on: ubuntu-latest
+    needs: [check_program_compilation]
+    container: epitechcontent/epitest-docker
+    timeout-minutes: 2
+    steps:
+      - uses: actions/checkout@v3
+      - run: |
+          echo"tests_run:" >> Makefile
+          echo"
+          make tests_run
+  push_to_mirror:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'push'
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - uses: pixta-dev/repository-mirroring-action@v1
+      - uses: pixta-dev/repository-mirroring-action@v1.0.1
         with:
-          target_repo_url:
-            ${{env.MIRROR_URL}}
-          ssh_private_key:
-            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
+          target_repo_url: ${{ env.MIRROR_URL }}
+          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
