heelpp

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -11,31 +11,55 @@ env:
   EXECUTABLES: ""
 
 jobs:
+  check_coding_style:
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - name: run check
+        uses: actions/checkout@v3
+      - name: run check script
+        shell: bash
+        run: check.sh $(pwd) $(pwd)
+      - name: parsing coding style
+        shell: bash
+        run: |
+          if [ -s $(pwd)/coding-style-reports.log ]; then
+            while read -r line; do
+              morM=$(echo $line | cut -d ':' -f3)
+              filename=$(echo $line | cut -d ':' -f1)
+              line=$(echo $line | cut -d ':' -f2)
+              error_type=$(echo $line | cut -d ':' -f4)
+              echo "::${morM} coding style error:${filename}\#L${line} ::${error_type}"
+              done < coding-style-reports.log
+            exit 1
+          fi
   check_program_compilation:
-    name: "Compile program"
+    runs-on: ubuntu-latest
+    steps:
+      - name: before
+        uses: actions/checkout@v3
+      - name: make
+        shell: bash
+        run: make
+        timeout-minutes: 2
+      - name: clean
+        shell: bash
+        run: make fclean
+  run_test:
+    needs: check_program_compilation
     runs-on: ubuntu-latest
     container:
       image: epitechcontent/epitest-docker
+    timeout-minutes: 2
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Compile program
-        run: make -j $(nproc)
+      - name: before
+        uses: actions/checkout@v3
+      - name: run tests
+        run: make tests_run
         timeout-minutes: 2
-
-      - name: Run make clean
-        run: make clean
-
-      - name: Verify executables
-        run: |
-          for exec in ${EXECUTABLES//,/ }; do
-            [[ -f $exec ]] && [[ -x $exec ]] || exit 1
-          done
-
-  mirror:
-    name: mirror to epitech
-    needs: check_program_compilation
+  push_to_mirror:
+    needs: run_test
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -43,6 +67,7 @@ jobs:
           fetch-depth: 0
       - uses: pixta-dev/repository-mirroring-action@v1
         with:
-          target_repo_url: ${{ env.MIRROR_URL }}
-          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
-
+          target_repo_url:
+            ${{env.MIRROR_URL}}
+          ssh_private_key:
+            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
